name: Docker CI/CD

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  # test:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Set up Docker
  #       uses: docker/setup-buildx-action@v2

  #     - name: Run tests in Docker
  #       run: |
  #         docker compose -f docker-compose.yml up --build --abort-on-container-exit

  #     - name: Cleanup test containers
  #       run: |
  #         docker compose -f docker-compose.yml down -v

  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/fesmu
            git pull
            docker compose down
            docker compose up -d --build
